name: Publish Python Package

on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'
  release:
    types: [published]

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine wheel setuptools
    
    - name: Build package
      run: |
        python -m build
        ls -la dist/
    
    - name: Install GitHub CLI
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
        && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
        && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
        && sudo apt update \
        && sudo apt install gh -y
    
    - name: Create GitHub Release with Python Package
      if: startsWith(github.ref, 'refs/tags/v')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Create a GitHub Release with the Python package as an asset
        TAG_NAME=${GITHUB_REF#refs/tags/}
        RELEASE_NAME="Face Recognition System $TAG_NAME"
        
        # Create release
        gh release create $TAG_NAME \
          --title "$RELEASE_NAME" \
          --notes "Python package release for Face Recognition System $TAG_NAME" \
          --draft=false \
          --prerelease=false \
          dist/*.tar.gz \
          dist/*.whl
        
        echo "✅ Python package uploaded to GitHub Release: $TAG_NAME"
    
    - name: Upload Package Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: python-package
        path: dist/
        retention-days: 30 