name: Publish Python Package

on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'
  release:
    types: [published]

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine wheel setuptools
    
    - name: Build package
      run: |
        python -m build
        ls -la dist/
    
    - name: Create GitHub Release with Python Package
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        name: "Face Recognition System ${{ github.ref_name }}"
        body: |
          ## Python Package Release ${{ github.ref_name }}
          
          This release contains the Face Recognition System Python package.
          
          ### Installation
          ```bash
          # Download and install wheel
          pip install face_recognition_system-*.whl
          
          # Or install source distribution
          pip install face_recognition_system-*.tar.gz
          ```
          
          ### Docker Image
          ```bash
          docker pull ghcr.io/ahmertsengol/face-auth-opencv:${{ github.ref_name }}
          ```
        files: |
          dist/*.tar.gz
          dist/*.whl
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload Package Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: python-package
        path: dist/
        retention-days: 30 